apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-app
  labels:
    app: httpbin-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin-app
  template:
    metadata:
      labels:
        app: httpbin-app
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-app
spec:
  type: ClusterIP
  selector:
    app: httpbin-app
  ports:
  - port: 80
    targetPort: 80